/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import Business.Customer.CustomerDirectory;
import Business.Organization.EcoSystem;
import Business.Restaurant.Menu;
import Business.Restaurant.Order;
import Business.Restaurant.Restaurant;
import Business.Restaurant.RestaurantMana;

import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class CustomerAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    private ArrayList<Menu>menuList;
    private UserAccount userAccount;
    private ArrayList<Order>orderList;
    private Restaurant restaurant;
    
    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public CustomerAreaJPanel(JPanel userProcessContainer, UserAccount account,EcoSystem system, Restaurant restaurant) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
      
        this.userAccount = account;
        this.menuList=restaurant.getMenuDirectory().getMenuList();
        this.system=system;
        this.restaurant=restaurant;
        this.orderList=restaurant.getOrderDirectory().getOrderList();
        valueLabel.setText(restaurant.getName());
        populateMenuInfoTable();
        populateOrderInfoTable();
        populateEvaluationTable();
    }
    public void populateEvaluationTable(){
        DefaultTableModel model = (DefaultTableModel)orderJTable.getModel();
        model.setRowCount(0);
        
        for(Order order:userAccount.getHistoryOrders()){
            
                Object[]row=new Object[5];
                row[0]=order.getOrderId();
                row[1]=order.getOrderMenu().getMenuName();
                row[2]=order.getStatus();

                for(WorkRequest request:restaurant.getWorkQueue().getWorkRequestList()){
                    if(order.getOrderId()==request.getOrder().getOrderId()){
                        row[3]=request.getStatus();
                    }
                }
                
                row[4]=order.getEvaluation();
                model.addRow(row);
            
        }
    }
   
    public void populateMenuInfoTable(){
        DefaultTableModel model=(DefaultTableModel)menuInfoJTable.getModel();
        model.setRowCount(0);
        
        for(Menu menu:menuList){
            Object[]row=new Object[3];
            row[0]=menu.getMenuId();
            row[1]=menu.getMenuName();
            row[2]=menu.getPrice();
            
            model.addRow(row);
        }
    }
    
    public void populateOrderInfoTable(){
        DefaultTableModel model=(DefaultTableModel)orderMenuJTable.getModel();
        model.setRowCount(0);
        
        for(Order order:userAccount.getHistoryOrders()){
            Object[]row=new Object[4];
            row[0]=order.getOrderId();
            row[1]=order.getOrderMenu().getMenuId();
            row[2]=order.getOrderMenu().getMenuName();
            row[3]=order.getOrderMenu().getPrice();
            
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        menuInfoJTable = new javax.swing.JTable();
        orderJButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        orderMenuJTable = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        evaluationJTextField = new javax.swing.JTextField();
        submitJButton = new javax.swing.JButton();

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("Place Your Order");

        valueLabel.setText("<value>");

        menuInfoJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Menu ID", "Menu Name", "Price"
            }
        ));
        jScrollPane2.setViewportView(menuInfoJTable);

        orderJButton.setText("Order");
        orderJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderJButtonActionPerformed(evt);
            }
        });

        orderMenuJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Order ID", "Menu ID", "Menu Name", "Price"
            }
        ));
        jScrollPane3.setViewportView(orderMenuJTable);

        orderJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Order ID", "Menu Name", "Order Status", "Distribution status", "Evaluation"
            }
        ));
        jScrollPane1.setViewportView(orderJTable);

        jLabel1.setText("Evaluation");

        evaluationJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evaluationJTextFieldActionPerformed(evt);
            }
        });

        submitJButton.setText("Submit");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(enterpriseLabel)
                        .addGap(44, 44, 44)
                        .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(30, 30, 30)
                                .addComponent(evaluationJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(submitJButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addComponent(orderJButton)))
                        .addGap(24, 24, 24)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(orderJButton)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(evaluationJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitJButton))
                .addContainerGap(54, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void orderJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow=menuInfoJTable.getSelectedRow(),col=0;
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select at least a row.", "INFORMATION", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Order o = new Order();
        o.setOrderMenu(menuList.get(selectedRow));
        o.setOrderCustomer(userAccount);
        orderList.add(o);
        userAccount.getHistoryOrders().add(o);
        populateOrderInfoTable();
        populateEvaluationTable();
    }//GEN-LAST:event_orderJButtonActionPerformed

    private void evaluationJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evaluationJTextFieldActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_evaluationJTextFieldActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow=orderJTable.getSelectedRow(),col=0;
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select at least a row.", "INFORMATION", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String evaluation=evaluationJTextField.getText();
        Order o = userAccount.getHistoryOrders().get(selectedRow);
        if(o.getStatus()==null){
            JOptionPane.showMessageDialog(this, "This order has not been processed!", "INFORMATION", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(o.getStatus().equals("Decline")){
            JOptionPane.showMessageDialog(this, "Your order has been cancelled", "INFORMATION", JOptionPane.ERROR_MESSAGE);
            return;
        }
        boolean found = false;
        for(WorkRequest request:restaurant.getWorkQueue().getWorkRequestList()){
            if(request.getOrder()==o){
                found = true;
                if(!request.getStatus().equals("Completed")) {
                    JOptionPane.showMessageDialog(this, "You haven't received the order yet!", "INFORMATION", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
        }
        if(!found) {
            JOptionPane.showMessageDialog(this, "You haven't received the order yet!", "INFORMATION", JOptionPane.ERROR_MESSAGE);
            return;
        }

        o.setEvaluation(evaluation);

        if (o.getEvaluation()== null ||o.getEvaluation().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please input the Evaluation!", "CREATE", JOptionPane.ERROR_MESSAGE);
            return;
        }
        populateEvaluationTable();
    }//GEN-LAST:event_submitJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JTextField evaluationJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable menuInfoJTable;
    private javax.swing.JButton orderJButton;
    private javax.swing.JTable orderJTable;
    private javax.swing.JTable orderMenuJTable;
    private javax.swing.JButton submitJButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
