/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.info5100.labpp.interfa;

import edu.neu.info5100.labpp.Person;
import java.io.*;
import java.awt.*;
import javax.swing.*;
import java.util.*;
/**
 *
 * @author kathe
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    private Person person;
    public CreateJPanel() {
        initComponents();
        javax.swing.filechooser.FileFilter[] ffs = fileChooser.getChoosableFileFilters();
        for (javax.swing.filechooser.FileFilter ff : ffs) {
            fileChooser.removeChoosableFileFilter(ff);
        }
        fileChooser.addChoosableFileFilter(new PersonPhotoFilter());
    }

    CreateJPanel(Person person) {
        this.person = person;
        initComponents();
        javax.swing.filechooser.FileFilter[] ffs = fileChooser.getChoosableFileFilters();
        for (javax.swing.filechooser.FileFilter ff : ffs) {
            fileChooser.removeChoosableFileFilter(ff);
        }
        fileChooser.addChoosableFileFilter(new PersonPhotoFilter());
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        sexButtonGroup = new javax.swing.ButtonGroup();
        generalInfoJPanel = new javax.swing.JPanel();
        firstNameLabel = new javax.swing.JLabel();
        phoneNumJLabel = new javax.swing.JLabel();
        lastNameJLabel = new javax.swing.JLabel();
        dobJLabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        phoneNumberTextField = new javax.swing.JTextField();
        dobTextField = new javax.swing.JTextField();
        personPhotoLabel = new javax.swing.JLabel();
        uploadJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        addressInfoJPanel = new javax.swing.JPanel();
        streetLabel = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        stateLabel = new javax.swing.JLabel();
        zipcodeLabel = new javax.swing.JLabel();
        streetTextField = new javax.swing.JTextField();
        cityTextField = new javax.swing.JTextField();
        stateTextField = new javax.swing.JTextField();
        zipcodeTextField = new javax.swing.JTextField();
        bankAccountInfoJPanel = new javax.swing.JPanel();
        bankNameLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        accountLabel = new javax.swing.JLabel();
        rountingLabel = new javax.swing.JLabel();
        bankNameTextField = new javax.swing.JTextField();
        accountTextField = new javax.swing.JTextField();
        rountingTextField = new javax.swing.JTextField();
        typeJComboBox = new javax.swing.JComboBox<>();
        driverLicenseJPanel = new javax.swing.JPanel();
        idLabel = new javax.swing.JLabel();
        doeLabel = new javax.swing.JLabel();
        sexLabel = new javax.swing.JLabel();
        doiLabel = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        doeTextField = new javax.swing.JTextField();
        doiTextField = new javax.swing.JTextField();
        femaleJRadioButton = new javax.swing.JRadioButton();
        maleJRadioButton = new javax.swing.JRadioButton();
        CreateProfileJButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(613, 400));
        setRequestFocusEnabled(false);

        generalInfoJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("General Information"));

        firstNameLabel.setText("First Name");

        phoneNumJLabel.setText("Phone Number");

        lastNameJLabel.setText("Last Name");

        dobJLabel.setText("Date of Birth(MM/DD/YYYY)");

        firstNameTextField.setPreferredSize(new java.awt.Dimension(7, 16));
        firstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextFieldActionPerformed(evt);
            }
        });

        lastNameTextField.setPreferredSize(new java.awt.Dimension(7, 16));

        phoneNumberTextField.setMinimumSize(new java.awt.Dimension(7, 16));
        phoneNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberTextFieldActionPerformed(evt);
            }
        });

        dobTextField.setPreferredSize(new java.awt.Dimension(7, 16));
        dobTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobTextFieldActionPerformed(evt);
            }
        });

        uploadJButton.setText("Upload");
        uploadJButton.setPreferredSize(new java.awt.Dimension(137, 22));
        uploadJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadJButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Personal Photo");

        javax.swing.GroupLayout generalInfoJPanelLayout = new javax.swing.GroupLayout(generalInfoJPanel);
        generalInfoJPanel.setLayout(generalInfoJPanelLayout);
        generalInfoJPanelLayout.setHorizontalGroup(
            generalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalInfoJPanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(generalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lastNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneNumJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dobJLabel))
                .addGap(33, 33, 33)
                .addGroup(generalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dobTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(generalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(uploadJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(personPhotoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );

        generalInfoJPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {dobJLabel, firstNameLabel, lastNameJLabel, phoneNumJLabel});

        generalInfoJPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {dobTextField, firstNameTextField, lastNameTextField, phoneNumberTextField});

        generalInfoJPanelLayout.setVerticalGroup(
            generalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalInfoJPanelLayout.createSequentialGroup()
                .addGroup(generalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(generalInfoJPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(generalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(generalInfoJPanelLayout.createSequentialGroup()
                                .addComponent(firstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addGroup(generalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lastNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(generalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(phoneNumJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(phoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(generalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dobJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dobTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(generalInfoJPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(uploadJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(personPhotoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        generalInfoJPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {dobJLabel, firstNameLabel, lastNameJLabel, phoneNumJLabel});

        generalInfoJPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {dobTextField, firstNameTextField, lastNameTextField, phoneNumberTextField});

        addressInfoJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Address Information"));

        streetLabel.setText("Street");

        cityLabel.setText("City");

        stateLabel.setText("State");

        zipcodeLabel.setText("Zipcode");

        streetTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streetTextFieldActionPerformed(evt);
            }
        });

        cityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityTextFieldActionPerformed(evt);
            }
        });

        stateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateTextFieldActionPerformed(evt);
            }
        });

        zipcodeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipcodeTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addressInfoJPanelLayout = new javax.swing.GroupLayout(addressInfoJPanel);
        addressInfoJPanel.setLayout(addressInfoJPanelLayout);
        addressInfoJPanelLayout.setHorizontalGroup(
            addressInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addressInfoJPanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(addressInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(streetLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(cityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(stateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(zipcodeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(addressInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(streetTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zipcodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(346, Short.MAX_VALUE))
        );

        addressInfoJPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cityLabel, cityTextField, stateLabel, stateTextField, streetLabel, streetTextField, zipcodeTextField});

        addressInfoJPanelLayout.setVerticalGroup(
            addressInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addressInfoJPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(addressInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(streetLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(streetTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(addressInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(addressInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(addressInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(zipcodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zipcodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        addressInfoJPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cityLabel, cityTextField, stateLabel, stateTextField, streetLabel, streetTextField, zipcodeLabel, zipcodeTextField});

        bankAccountInfoJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Bank Account Information"));

        bankNameLabel.setText("Bank Name");
        bankNameLabel.setPreferredSize(new java.awt.Dimension(44, 16));

        typeLabel.setText("Type");

        accountLabel.setText("Account");

        rountingLabel.setText("Rounting");

        bankNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankNameTextFieldActionPerformed(evt);
            }
        });

        accountTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountTextFieldActionPerformed(evt);
            }
        });

        rountingTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rountingTextFieldActionPerformed(evt);
            }
        });

        typeJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Saving", "Checking" }));
        typeJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeJComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bankAccountInfoJPanelLayout = new javax.swing.GroupLayout(bankAccountInfoJPanel);
        bankAccountInfoJPanel.setLayout(bankAccountInfoJPanelLayout);
        bankAccountInfoJPanelLayout.setHorizontalGroup(
            bankAccountInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bankAccountInfoJPanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(bankAccountInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rountingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bankNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(bankAccountInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bankAccountInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(bankAccountInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(typeJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(accountTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(rountingTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bankNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(344, 344, 344))
        );
        bankAccountInfoJPanelLayout.setVerticalGroup(
            bankAccountInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bankAccountInfoJPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(bankAccountInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bankNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bankNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(bankAccountInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bankAccountInfoJPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(typeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(typeJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(bankAccountInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bankAccountInfoJPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(accountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(accountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(bankAccountInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rountingTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rountingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        driverLicenseJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Driver License Information"));

        idLabel.setText("ID");

        doeLabel.setText("Date of Expiry");

        sexLabel.setText("Sex");

        doiLabel.setText("Date of Issue");

        idTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextFieldActionPerformed(evt);
            }
        });

        doeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doeTextFieldActionPerformed(evt);
            }
        });

        doiTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doiTextFieldActionPerformed(evt);
            }
        });

        sexButtonGroup.add(femaleJRadioButton);
        femaleJRadioButton.setText("female");
        femaleJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleJRadioButtonActionPerformed(evt);
            }
        });

        sexButtonGroup.add(maleJRadioButton);
        maleJRadioButton.setText("male");

        javax.swing.GroupLayout driverLicenseJPanelLayout = new javax.swing.GroupLayout(driverLicenseJPanel);
        driverLicenseJPanel.setLayout(driverLicenseJPanelLayout);
        driverLicenseJPanelLayout.setHorizontalGroup(
            driverLicenseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(driverLicenseJPanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(driverLicenseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(driverLicenseJPanelLayout.createSequentialGroup()
                        .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(driverLicenseJPanelLayout.createSequentialGroup()
                        .addComponent(doeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(doeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(driverLicenseJPanelLayout.createSequentialGroup()
                        .addComponent(doiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(doiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(driverLicenseJPanelLayout.createSequentialGroup()
                        .addComponent(sexLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(femaleJRadioButton)
                        .addGap(27, 27, 27)
                        .addComponent(maleJRadioButton))))
        );
        driverLicenseJPanelLayout.setVerticalGroup(
            driverLicenseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(driverLicenseJPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(driverLicenseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(driverLicenseJPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(driverLicenseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(driverLicenseJPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(doeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(doeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(driverLicenseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(driverLicenseJPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(doiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(doiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(driverLicenseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(driverLicenseJPanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(sexLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(femaleJRadioButton)
                    .addComponent(maleJRadioButton)))
        );

        CreateProfileJButton.setText("Create");
        CreateProfileJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateProfileJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bankAccountInfoJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(driverLicenseJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressInfoJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(generalInfoJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(CreateProfileJButton)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addressInfoJPanel, bankAccountInfoJPanel, driverLicenseJPanel, generalInfoJPanel});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(CreateProfileJButton))
                    .addComponent(generalInfoJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(addressInfoJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(bankAccountInfoJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(driverLicenseJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {addressInfoJPanel, bankAccountInfoJPanel, driverLicenseJPanel, generalInfoJPanel});

    }// </editor-fold>//GEN-END:initComponents

    private void firstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextFieldActionPerformed

    private void phoneNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumberTextFieldActionPerformed

    private void dobTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobTextFieldActionPerformed

    private void uploadJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadJButtonActionPerformed
        // TODO add your handling code here:
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            ImageIcon imgIcon = new ImageIcon(file.getAbsolutePath());
            int imgWidth = imgIcon.getIconWidth();
            int imgHeight = imgIcon.getIconHeight();
            double imgRatio = Math.min(1.0 * personPhotoLabel.getWidth() / imgWidth, 1.0 * personPhotoLabel.getHeight() / imgHeight);
            int newWidth = (int)(imgWidth * imgRatio);
            int newHeight = (int)(imgHeight * imgRatio);
            imgIcon.setImage(imgIcon.getImage().getScaledInstance(newWidth, newHeight, Image.SCALE_DEFAULT));
            personPhotoLabel.setIcon(imgIcon);
        } else {
            System.out.println("File access cancelled by user.");
        }
        
    }//GEN-LAST:event_uploadJButtonActionPerformed

    private void streetTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streetTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_streetTextFieldActionPerformed

    private void cityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityTextFieldActionPerformed

    private void stateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateTextFieldActionPerformed

    private void zipcodeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipcodeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zipcodeTextFieldActionPerformed

    private void bankNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bankNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bankNameTextFieldActionPerformed

    private void accountTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountTextFieldActionPerformed

    private void rountingTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rountingTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rountingTextFieldActionPerformed

    private void typeJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeJComboBoxActionPerformed
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_typeJComboBoxActionPerformed

    private void idTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextFieldActionPerformed

    private void doeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doeTextFieldActionPerformed

    private void doiTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doiTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doiTextFieldActionPerformed

    private void CreateProfileJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateProfileJButtonActionPerformed
        // TODO add your handling code here:
        //Binding the user input to the person object
        //general info
          person.setFirstName(firstNameTextField.getText()) ;
          person.setLastName(lastNameTextField.getText());
          person.setPhoneNumber(phoneNumberTextField.getText());
          person.setDob(dobTextField.getText());
          person.setImg(personPhotoLabel.getIcon());
          //address info
          person.setState(stateTextField.getText());  
          person.setStreet(streetTextField.getText());
          person.setCity(cityTextField.getText());
          person.setZipcode(zipcodeTextField.getText());
          //bank info
          person.setBankName(bankNameTextField.getText());
          person.setAccount(accountTextField.getText());
          person.setRounting(rountingTextField.getText());
          person.setAccountType(typeJComboBox.getSelectedIndex());
          //JComboBox cb = (JComboBox)evt.getSource();
          //String newSelection = (String)cb.getSelectedItem();
          
          //driver license
          person.setDoe(doeTextField.getText());
          person.setDoi(doiTextField.getText());
          person.setId(idTextField.getText());
          for (Enumeration<AbstractButton> buttons=sexButtonGroup.getElements();buttons.hasMoreElements();){
              AbstractButton button=buttons.nextElement();
              if(button.isSelected()){
                  person.setSex(button.getText());
              }
          }

          //Prompt user that person was successfully created;
          
          JOptionPane.showMessageDialog(null,"Create Person Successfully");
    }//GEN-LAST:event_CreateProfileJButtonActionPerformed

    private void femaleJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleJRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleJRadioButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateProfileJButton;
    private javax.swing.JLabel accountLabel;
    private javax.swing.JTextField accountTextField;
    private javax.swing.JPanel addressInfoJPanel;
    private javax.swing.JPanel bankAccountInfoJPanel;
    private javax.swing.JLabel bankNameLabel;
    private javax.swing.JTextField bankNameTextField;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JLabel dobJLabel;
    private javax.swing.JTextField dobTextField;
    private javax.swing.JLabel doeLabel;
    private javax.swing.JTextField doeTextField;
    private javax.swing.JLabel doiLabel;
    private javax.swing.JTextField doiTextField;
    private javax.swing.JPanel driverLicenseJPanel;
    private javax.swing.JRadioButton femaleJRadioButton;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JPanel generalInfoJPanel;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lastNameJLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JRadioButton maleJRadioButton;
    private javax.swing.JLabel personPhotoLabel;
    private javax.swing.JLabel phoneNumJLabel;
    private javax.swing.JTextField phoneNumberTextField;
    private javax.swing.JLabel rountingLabel;
    private javax.swing.JTextField rountingTextField;
    private javax.swing.ButtonGroup sexButtonGroup;
    private javax.swing.JLabel sexLabel;
    private javax.swing.JLabel stateLabel;
    private javax.swing.JTextField stateTextField;
    private javax.swing.JLabel streetLabel;
    private javax.swing.JTextField streetTextField;
    private javax.swing.JComboBox<String> typeJComboBox;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JButton uploadJButton;
    private javax.swing.JLabel zipcodeLabel;
    private javax.swing.JTextField zipcodeTextField;
    // End of variables declaration//GEN-END:variables
}
