/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.info5100.labpp.interfa;

import edu.neu.info5100.labpp.Person;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.Icon;

/**
 *
 * @author kathe
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    public ViewJPanel(Person person) {
        initComponents();
        displayPerson(person);
    }
    
      private void displayPerson(Person person){
          //general info
         String personFirstName=person.getFirstName();
         firstNameTextField.setText(personFirstName);
         
         String personLastName=person.getLastName();
         lastNameTextField.setText(personLastName);
         
         String personDob=person.getDob();
         dobTextField.setText(personDob);
          
         String personPhoneNumber=person.getPhoneNumber();
         phoneNumberTextField.setText(personPhoneNumber);
         
         Icon personPhoto=person.getImg();
         personPhotoLabel.setIcon(personPhoto);
         //address info
         String personStreet=person.getStreet();
         streetTextField.setText(personStreet);
         
         String personCity=person.getCity();
         cityTextField.setText(personCity);
         
         String personState=person.getState();
         stateTextField.setText(personState);
         
         String personZipcode=person.getZipcode();
         zipcodeTextField.setText(personZipcode);
         //bank info
         String personBankName=person.getBankName();
         bankNameTextField.setText(personBankName);
         
         String personAccount=person.getAccount();
         accountTextField.setText(personAccount);
         
         String personRounting=person.getRounting();
         rountingTextField.setText(personRounting);
         
         int personAccountType=person.getAccountType();
         typeJComboBox.setSelectedIndex(personAccountType);
         //driver license
         String personDoe=person.getDoe();
         doeTextField.setText(personDoe);
         
         String personDoi=person.getDoi();
         doiTextField.setText(personDoi);
         
         String personId=person.getId();
         idTextField.setText(personId);
         
         String personSex=person.getSex();
         for (Enumeration<AbstractButton> buttons=sexButtonGroup.getElements();buttons.hasMoreElements();){
              AbstractButton button=buttons.nextElement();
              if(button.getText() == personSex){
                  button.setSelected(true);
              } else {
                  button.setSelected(false);
              }
          }
         
    }  
        
    
         ViewJPanel() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexButtonGroup = new javax.swing.ButtonGroup();
        driverLicenseJPanel = new javax.swing.JPanel();
        idLabel = new javax.swing.JLabel();
        doeLabel = new javax.swing.JLabel();
        sexLabel = new javax.swing.JLabel();
        doiLabel = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        doeTextField = new javax.swing.JTextField();
        doiTextField = new javax.swing.JTextField();
        femaleJRadioButton = new javax.swing.JRadioButton();
        maleJRadioButton = new javax.swing.JRadioButton();
        bankAccountInfoJPanel = new javax.swing.JPanel();
        bankNameLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        accountLabel = new javax.swing.JLabel();
        rountingLabel = new javax.swing.JLabel();
        bankNameTextField = new javax.swing.JTextField();
        accountTextField = new javax.swing.JTextField();
        rountingTextField = new javax.swing.JTextField();
        typeJComboBox = new javax.swing.JComboBox<>();
        addressInfoJPanel = new javax.swing.JPanel();
        streetLabel = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        stateLabel = new javax.swing.JLabel();
        zipcodeLabel = new javax.swing.JLabel();
        streetTextField = new javax.swing.JTextField();
        cityTextField = new javax.swing.JTextField();
        stateTextField = new javax.swing.JTextField();
        zipcodeTextField = new javax.swing.JTextField();
        generalInfoJPanel = new javax.swing.JPanel();
        firstNameLabel = new javax.swing.JLabel();
        phoneNumJLabel = new javax.swing.JLabel();
        lastNameJLabel = new javax.swing.JLabel();
        dobJLabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        phoneNumberTextField = new javax.swing.JTextField();
        dobTextField = new javax.swing.JTextField();
        personPhotoLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        driverLicenseJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Driver License Information"));

        idLabel.setText("ID");

        doeLabel.setText("Date of Expiry");

        sexLabel.setText("Sex");

        doiLabel.setText("Date of Issue");

        idTextField.setEditable(false);
        idTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextFieldActionPerformed(evt);
            }
        });

        doeTextField.setEditable(false);
        doeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doeTextFieldActionPerformed(evt);
            }
        });

        doiTextField.setEditable(false);
        doiTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doiTextFieldActionPerformed(evt);
            }
        });

        sexButtonGroup.add(femaleJRadioButton);
        femaleJRadioButton.setText("female");
        femaleJRadioButton.setEnabled(false);
        femaleJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleJRadioButtonActionPerformed(evt);
            }
        });

        sexButtonGroup.add(maleJRadioButton);
        maleJRadioButton.setText("male");
        maleJRadioButton.setEnabled(false);
        maleJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleJRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout driverLicenseJPanelLayout = new javax.swing.GroupLayout(driverLicenseJPanel);
        driverLicenseJPanel.setLayout(driverLicenseJPanelLayout);
        driverLicenseJPanelLayout.setHorizontalGroup(
            driverLicenseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(driverLicenseJPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(driverLicenseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(driverLicenseJPanelLayout.createSequentialGroup()
                        .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(driverLicenseJPanelLayout.createSequentialGroup()
                        .addComponent(doeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(doeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(driverLicenseJPanelLayout.createSequentialGroup()
                        .addComponent(doiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(doiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(driverLicenseJPanelLayout.createSequentialGroup()
                        .addComponent(sexLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(femaleJRadioButton)
                        .addGap(27, 27, 27)
                        .addComponent(maleJRadioButton))))
        );
        driverLicenseJPanelLayout.setVerticalGroup(
            driverLicenseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(driverLicenseJPanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(driverLicenseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(driverLicenseJPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(driverLicenseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(driverLicenseJPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(doeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(doeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(driverLicenseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(driverLicenseJPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(doiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(doiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(driverLicenseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(driverLicenseJPanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(sexLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(femaleJRadioButton)
                    .addComponent(maleJRadioButton)))
        );

        bankAccountInfoJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Bank Account Information"));
        bankAccountInfoJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bankNameLabel.setText("Bank Name");
        bankAccountInfoJPanel.add(bankNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 32, 140, 21));

        typeLabel.setText("Type");
        bankAccountInfoJPanel.add(typeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 61, 140, 21));

        accountLabel.setText("Account");
        bankAccountInfoJPanel.add(accountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 98, 140, 21));

        rountingLabel.setText("Rounting");
        bankAccountInfoJPanel.add(rountingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 126, 140, 21));

        bankNameTextField.setEditable(false);
        bankNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankNameTextFieldActionPerformed(evt);
            }
        });
        bankAccountInfoJPanel.add(bankNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 31, 163, -1));

        accountTextField.setEditable(false);
        accountTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountTextFieldActionPerformed(evt);
            }
        });
        bankAccountInfoJPanel.add(accountTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 163, -1));

        rountingTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rountingTextFieldActionPerformed(evt);
            }
        });
        bankAccountInfoJPanel.add(rountingTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 163, -1));

        typeJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Saving", "Checking" }));
        typeJComboBox.setEnabled(false);
        typeJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeJComboBoxActionPerformed(evt);
            }
        });
        bankAccountInfoJPanel.add(typeJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 60, 163, -1));

        addressInfoJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Address Information"));
        addressInfoJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        streetLabel.setText("Street");
        addressInfoJPanel.add(streetLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 32, 129, 21));

        cityLabel.setText("City");
        addressInfoJPanel.add(cityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 67, 129, 21));

        stateLabel.setText("State");
        addressInfoJPanel.add(stateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 95, 129, 22));

        zipcodeLabel.setText("Zipcode");
        addressInfoJPanel.add(zipcodeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 126, 129, 18));

        streetTextField.setEditable(false);
        streetTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streetTextFieldActionPerformed(evt);
            }
        });
        addressInfoJPanel.add(streetTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 31, 161, -1));

        cityTextField.setEditable(false);
        cityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityTextFieldActionPerformed(evt);
            }
        });
        addressInfoJPanel.add(cityTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 66, 161, -1));

        stateTextField.setEditable(false);
        stateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateTextFieldActionPerformed(evt);
            }
        });
        addressInfoJPanel.add(stateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 95, 161, -1));

        zipcodeTextField.setEditable(false);
        zipcodeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipcodeTextFieldActionPerformed(evt);
            }
        });
        addressInfoJPanel.add(zipcodeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 124, 161, -1));

        generalInfoJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("General Information"));
        generalInfoJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        firstNameLabel.setText("First Name");
        generalInfoJPanel.add(firstNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 34, 162, -1));

        phoneNumJLabel.setText("Phone Number");
        generalInfoJPanel.add(phoneNumJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 111, 162, -1));

        lastNameJLabel.setText("Last Name");
        generalInfoJPanel.add(lastNameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 69, 162, -1));

        dobJLabel.setText("Date of Birth(MM/DD/YYYY)");
        generalInfoJPanel.add(dobJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 151, -1, -1));

        firstNameTextField.setEditable(false);
        firstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextFieldActionPerformed(evt);
            }
        });
        generalInfoJPanel.add(firstNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 31, 162, -1));

        lastNameTextField.setEditable(false);
        generalInfoJPanel.add(lastNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 66, 162, -1));

        phoneNumberTextField.setEditable(false);
        phoneNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberTextFieldActionPerformed(evt);
            }
        });
        generalInfoJPanel.add(phoneNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 108, 162, -1));

        dobTextField.setEditable(false);
        dobTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobTextFieldActionPerformed(evt);
            }
        });
        generalInfoJPanel.add(dobTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 148, 162, -1));
        generalInfoJPanel.add(personPhotoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 31, 115, 139));

        jLabel1.setText("Personal Photo");
        generalInfoJPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 34, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 744, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(bankAccountInfoJPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addressInfoJPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(generalInfoJPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(driverLicenseJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(116, 116, 116)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 786, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(generalInfoJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(addressInfoJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(bankAccountInfoJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(driverLicenseJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(142, 142, 142)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void idTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextFieldActionPerformed

    private void doeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doeTextFieldActionPerformed

    private void doiTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doiTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doiTextFieldActionPerformed

    private void bankNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bankNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bankNameTextFieldActionPerformed

    private void accountTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountTextFieldActionPerformed

    private void rountingTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rountingTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rountingTextFieldActionPerformed

    private void typeJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeJComboBoxActionPerformed

    private void streetTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streetTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_streetTextFieldActionPerformed

    private void cityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityTextFieldActionPerformed

    private void stateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateTextFieldActionPerformed

    private void zipcodeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipcodeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zipcodeTextFieldActionPerformed

    private void firstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextFieldActionPerformed

    private void phoneNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumberTextFieldActionPerformed

    private void dobTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobTextFieldActionPerformed

    private void femaleJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleJRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleJRadioButtonActionPerformed

    private void maleJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleJRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleJRadioButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountLabel;
    private javax.swing.JTextField accountTextField;
    private javax.swing.JPanel addressInfoJPanel;
    private javax.swing.JPanel bankAccountInfoJPanel;
    private javax.swing.JLabel bankNameLabel;
    private javax.swing.JTextField bankNameTextField;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JLabel dobJLabel;
    private javax.swing.JTextField dobTextField;
    private javax.swing.JLabel doeLabel;
    private javax.swing.JTextField doeTextField;
    private javax.swing.JLabel doiLabel;
    private javax.swing.JTextField doiTextField;
    private javax.swing.JPanel driverLicenseJPanel;
    private javax.swing.JRadioButton femaleJRadioButton;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JPanel generalInfoJPanel;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lastNameJLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JRadioButton maleJRadioButton;
    private javax.swing.JLabel personPhotoLabel;
    private javax.swing.JLabel phoneNumJLabel;
    private javax.swing.JTextField phoneNumberTextField;
    private javax.swing.JLabel rountingLabel;
    private javax.swing.JTextField rountingTextField;
    private javax.swing.ButtonGroup sexButtonGroup;
    private javax.swing.JLabel sexLabel;
    private javax.swing.JLabel stateLabel;
    private javax.swing.JTextField stateTextField;
    private javax.swing.JLabel streetLabel;
    private javax.swing.JTextField streetTextField;
    private javax.swing.JComboBox<String> typeJComboBox;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JLabel zipcodeLabel;
    private javax.swing.JTextField zipcodeTextField;
    // End of variables declaration//GEN-END:variables
}
