package userinterface.RestaurantAdminRole;


import Business.Organization.EcoSystem;
import Business.Restaurant.Menu;
import Business.Restaurant.Restaurant;
import Business.Restaurant.RestaurantMana;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author  raunak
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    RestaurantMana manager;
    Restaurant restaurant;
    private EcoSystem system;
    /** Creates new form AdminWorkAreaJPanel */
    public AdminWorkAreaJPanel(JPanel userProcessContainer, RestaurantMana manager, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.manager = manager;
        this.restaurant = manager.getManagedRestaurant();
        this.system = system;
        valueLabel.setText(manager.getManagedRestaurant().getName());
      
        //valueLabel.setText();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */  
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageRestaurantInfoJButton = new javax.swing.JButton();
        manageMenuJButton = new javax.swing.JButton();
        manageOrdersJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        workRequestJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("My Work Area -Adminstrative Role");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        manageRestaurantInfoJButton.setText("Manage Restaurant Info");
        manageRestaurantInfoJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageRestaurantInfoJButtonActionPerformed(evt);
            }
        });
        add(manageRestaurantInfoJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 160, -1));

        manageMenuJButton.setText("Manage menu");
        manageMenuJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageMenuJButtonActionPerformed(evt);
            }
        });
        add(manageMenuJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 160, -1));

        manageOrdersJButton.setText("Manage Orders");
        manageOrdersJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrdersJButtonActionPerformed(evt);
            }
        });
        add(manageOrdersJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 160, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("Restaurant :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 120, 30));

        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 130, -1));

        workRequestJButton.setText("Send Work Request");
        workRequestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workRequestJButtonActionPerformed(evt);
            }
        });
        add(workRequestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 170, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void manageRestaurantInfoJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageRestaurantInfoJButtonActionPerformed
        // TODO add your handling code here:
        ChooseDeliverymanJPanel chooseDeliverymanJPanel=new ChooseDeliverymanJPanel(userProcessContainer,system,restaurant);
        userProcessContainer.add("chooseDeliverymanJPanel",chooseDeliverymanJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageRestaurantInfoJButtonActionPerformed

    private void manageMenuJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageMenuJButtonActionPerformed
        MenuInfoJPanel menuInfoJPanel=new MenuInfoJPanel(userProcessContainer, manager);
        userProcessContainer.add("menuInfoJPanel", menuInfoJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageMenuJButtonActionPerformed

    private void manageOrdersJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrdersJButtonActionPerformed
        OrderInfoJPanel orderInfoJPanel=new OrderInfoJPanel(userProcessContainer, manager.getManagedRestaurant());
         userProcessContainer.add("orderInfoJPanel", orderInfoJPanel);
          CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOrdersJButtonActionPerformed

    private void workRequestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workRequestJButtonActionPerformed
        // TODO add your handling code here:
        SendRequestTodDeliverymanJPanel sendRequestTodDeliverymanJPanel=new SendRequestTodDeliverymanJPanel(userProcessContainer,manager);
        userProcessContainer.add("sendRequestTodDeliveryman", sendRequestTodDeliverymanJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_workRequestJButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageMenuJButton;
    private javax.swing.JButton manageOrdersJButton;
    private javax.swing.JButton manageRestaurantInfoJButton;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JButton workRequestJButton;
    // End of variables declaration//GEN-END:variables
    
}
